#开发环境配置

server:
  # 服务端口
  port: 8000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Ihavenoidea@0
    url: jdbc:mysql://localhost:9903/lin-cms?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root


# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug




